// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzWbiCoMRu_rKKP_5x6mT7OmBvVyNXcmg',
    appId: '1:213045860705:web:a44fd7f46c651e66eb8d20',
    messagingSenderId: '213045860705',
    projectId: 'sw1-p2-odoo',
    authDomain: 'sw1-p2-odoo.firebaseapp.com',
    storageBucket: 'sw1-p2-odoo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQd2tvClU7k3Djavlosmz0d49qY2Esp6E',
    appId: '1:213045860705:android:cefe0ff2b340bb84eb8d20',
    messagingSenderId: '213045860705',
    projectId: 'sw1-p2-odoo',
    storageBucket: 'sw1-p2-odoo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARqYY07p4tDonrp5WOQNDdJiNHsJm21v0',
    appId: '1:213045860705:ios:c1d07f5ec1556527eb8d20',
    messagingSenderId: '213045860705',
    projectId: 'sw1-p2-odoo',
    storageBucket: 'sw1-p2-odoo.firebasestorage.app',
    iosBundleId: 'com.example.agendaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARqYY07p4tDonrp5WOQNDdJiNHsJm21v0',
    appId: '1:213045860705:ios:c1d07f5ec1556527eb8d20',
    messagingSenderId: '213045860705',
    projectId: 'sw1-p2-odoo',
    storageBucket: 'sw1-p2-odoo.firebasestorage.app',
    iosBundleId: 'com.example.agendaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzWbiCoMRu_rKKP_5x6mT7OmBvVyNXcmg',
    appId: '1:213045860705:web:ba44df2059d2e08beb8d20',
    messagingSenderId: '213045860705',
    projectId: 'sw1-p2-odoo',
    authDomain: 'sw1-p2-odoo.firebaseapp.com',
    storageBucket: 'sw1-p2-odoo.firebasestorage.app',
  );

}